services:
  solar-app:
    build:
      context: ..
      dockerfile: docker/dockerfile
    ports:
      - 8080:8080
    env_file:
      - ../.env
    environment:
      - ENV=production
    depends_on:
      - postgres-db
  postgres-db:
    hostname: postgres
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/:rw
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=solar
volumes:
  postgres_data:
    driver: local